import { describe, expect, it } from 'vitest';
import { extractHeader } from '../src/cvox/header.js';
import { parseCvox } from '../src/cvox/parse.js';
import { serializeCvox } from '../src/cvox/serialize.js';
import type { Cvox } from '../src/cvox/types.js';

function unwrap(input: string): Cvox {
  const r = parseCvox(input);
  if (!r.ok) throw new Error(`parse failed: ${r.message}`);
  return r.value;
}

describe('extractHeader — pure boundary rule', () => {
  it('returns [] when the first line is a declaration', () => {
    expect(extractHeader('palette #F00\npart p\nsize 1 1 1\nvoxels { 0 }')).toEqual([]);
  });

  it('returns [] when the file is empty', () => {
    expect(extractHeader('')).toEqual([]);
  });

  it('captures a single header comment verbatim (keeps leading `//`)', () => {
    const text = '// MIT License\npalette #F00';
    expect(extractHeader(text)).toEqual(['// MIT License']);
  });

  it('captures multiple consecutive header comments', () => {
    const text = '// Line 1\n// Line 2\n// Line 3\npalette #F00';
    expect(extractHeader(text)).toEqual(['// Line 1', '// Line 2', '// Line 3']);
  });

  it('preserves blank lines BETWEEN header comments (interspersed)', () => {
    const text = '// Block A\n\n// Block B\npalette #F00';
    expect(extractHeader(text)).toEqual(['// Block A', '', '// Block B']);
  });

  it('trims leading blank lines (before first comment)', () => {
    const text = '\n\n// header\npalette #F00';
    expect(extractHeader(text)).toEqual(['// header']);
  });

  it('trims trailing blank lines (between last comment and palette)', () => {
    const text = '// header\n\n\npalette #F00';
    expect(extractHeader(text)).toEqual(['// header']);
  });

  it('stops at the first non-comment, non-blank token', () => {
    // A comment AFTER the palette is not part of the header.
    const text = '// header\npalette #F00 // inline comment\n// post-palette comment';
    expect(extractHeader(text)).toEqual(['// header']);
  });

  it('preserves indentation and trailing spaces on header lines', () => {
    const text = '  // indented\n// plain  \npalette #F00';
    expect(extractHeader(text)).toEqual(['  // indented', '// plain  ']);
  });
});

describe('parseCvox — header attachment', () => {
  it('omits `header` field entirely when there is no header', () => {
    const cvox = unwrap('palette #F00\npart p\nsize 1 1 1\nvoxels { 0 }');
    expect(cvox.header).toBeUndefined();
  });

  it('attaches header to the AST when present', () => {
    const cvox = unwrap('// MIT License\n// Copyright 2026\npalette #F00\npart p\nsize 1 1 1\nvoxels { 0 }');
    expect(cvox.header).toEqual(['// MIT License', '// Copyright 2026']);
  });

  it('does not affect line numbers in parse errors', () => {
    // Header occupies 2 lines; the error message should reference line 5,
    // not line 3 (header-stripped) — header extraction is non-destructive.
    const r = parseCvox('// line 1\n// line 2\npalette #F00\npart p\nrot 0 0 0');
    expect(r.ok).toBe(false);
    if (r.ok) throw new Error('expected failure');
    expect(r.message).toMatch(/line 5/);
  });
});

describe('serializeCvox — header emission', () => {
  it('omits header section when AST has no header', () => {
    const cvox = unwrap('palette #F00\npart p\nsize 1 1 1\nvoxels { 0 }');
    const text = serializeCvox(cvox);
    expect(text.startsWith('palette ')).toBe(true);
  });

  it('emits header lines verbatim, then a single blank line, then palette', () => {
    const cvox = unwrap('// hello\n// world\npalette #F00\npart p\nsize 1 1 1\nvoxels { 0 }');
    const text = serializeCvox(cvox);
    expect(text.startsWith('// hello\n// world\n\npalette ')).toBe(true);
  });

  it('preserves interspersed blank lines inside the header', () => {
    const cvox = unwrap('// A\n\n// B\npalette #F00\npart p\nsize 1 1 1\nvoxels { 0 }');
    const text = serializeCvox(cvox);
    expect(text.startsWith('// A\n\n// B\n\npalette ')).toBe(true);
  });
});

describe('parse → serialize → parse round-trip with header', () => {
  function roundTrip(input: string): void {
    const first = unwrap(input);
    const second = unwrap(serializeCvox(first));
    expect(second).toEqual(first);
  }

  it('round-trips a single header line', () => {
    roundTrip('// MIT License\npalette #F00\npart p\nsize 1 1 1\nvoxels { 0 }');
  });

  it('round-trips multi-line headers with interspersed blanks', () => {
    roundTrip(
      '// Cuboidy model: wolf\n// Author: Marble\n\n// Generated by cuboidy-export v1.0\npalette #F00\npart p\nsize 1 1 1\nvoxels { 0 }',
    );
  });
});

describe('serializeCvox — header idempotence', () => {
  it('re-serializing a header-bearing canonical text is a fixed point', () => {
    const input = '// header\npalette #F00\npart p\nsize 1 1 1\nvoxels { 0 }';
    const once = serializeCvox(unwrap(input));
    const twice = serializeCvox(unwrap(once));
    expect(twice).toBe(once);
  });

  it('normalizes multiple blank-line separators to a single blank line', () => {
    // Source has 3 blank lines between header and palette; canonical
    // output should collapse to 1.
    const cvox = unwrap('// header\n\n\n\npalette #F00\npart p\nsize 1 1 1\nvoxels { 0 }');
    const text = serializeCvox(cvox);
    expect(text).toContain('// header\n\npalette ');
    expect(text).not.toContain('// header\n\n\n');
  });
});

describe('inline comments — explicitly NOT preserved', () => {
  it('inline `//` after a declaration is dropped on round-trip', () => {
    const cvox = unwrap('palette #F00 // gold\npart p\nsize 1 1 1\nvoxels { 0 }');
    expect(cvox.header).toBeUndefined();
    const text = serializeCvox(cvox);
    expect(text).not.toContain('gold');
  });

  it('comments between declarations are dropped', () => {
    const cvox = unwrap('palette #F00\n// between\npart p\nsize 1 1 1\nvoxels { 0 }');
    expect(cvox.header).toBeUndefined();
    const text = serializeCvox(cvox);
    expect(text).not.toContain('between');
  });
});
