// SPEC §7.X: File header extraction.
//
// The file header is the sequence of `//` comment lines (with optional
// interspersed blank lines) appearing before the first declaration in a
// `voxels.cvox` file. Header content is preserved verbatim — leading `//`,
// internal spacing, and case — so that license notices and "generated by"
// markers round-trip without normalization.
//
// Boundary rule (the user-confirmed "candidate B" from design):
//   1. Walk lines from the top.
//   2. The first non-blank, non-comment line marks where the body begins.
//   3. The header is the candidate range [0, bodyStart) with leading and
//      trailing blank lines trimmed (those blanks are formatting between
//      the file edge / palette declaration and the header content, not
//      part of the header itself).
//
// Returns [] when the file has no header content. Never returns undefined
// or includes the body-starting line.

const COMMENT_PREFIX = '//';

export function extractHeader(text: string): string[] {
  const lines = text.split(/\r?\n/);
  let bodyStart = lines.length;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i]!.trim();
    if (trimmed.length === 0) continue;
    if (trimmed.startsWith(COMMENT_PREFIX)) continue;
    bodyStart = i;
    break;
  }
  let start = 0;
  let end = bodyStart;
  while (start < end && lines[start]!.trim().length === 0) start++;
  while (end > start && lines[end - 1]!.trim().length === 0) end--;
  return lines.slice(start, end);
}
